modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/ResourcePandas/issues"
license="MIT"

[[mods]]
modId="resourcepandas"
version="${file.jarVersion}"
displayName="Resource Panda's"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resource-pandas"
authors="Mrbysco, Drullkus"
credits="Drullkus for the idea"
description='''
A snotty goldmine
'''
[[dependencies.resourcepandas]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"