modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/ResourcePandas/issues"
license="MIT"

[[mods]]
modId="resourcepandas"
version="${file.jarVersion}"
displayName="Resource Panda's"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resource-pandas"
authors="Mrbysco, Drullkus"
credits="Drullkus for the idea"
description='''
A snotty goldmine
'''
[[dependencies.resourcepandas]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.resourcepandas]]
modId="forge"
mandatory=true
versionRange="[40.0.35,)"
ordering="NONE"
side="BOTH"