modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/ResourcePandas/issues"
license="MIT"

[[mods]]
modId="resourcepandas"
version="${file.jarVersion}"
displayName="Resource Panda's"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resource-pandas"
authors="Mrbysco, Drullkus"
credits="Drullkus for the idea"
description='''
A snotty goldmine
'''
[[dependencies.resourcepandas]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.resourcepandas]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"