modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ResourcePandas/issues"
license="MIT"

[[mods]]
modId="resourcepandas"
version="${file.jarVersion}"
displayName="Resource Panda's"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resource-pandas"
authors="Mrbysco, Drullkus"
credits="Drullkus for the idea"
description='''
A snotty goldmine
'''
[[dependencies.resourcepandas]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.resourcepandas]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.31-beta,)"
ordering="NONE"
side="BOTH"